// Códigos de provincia argentina que exige la API de Envia.com (máx. 2
// caracteres). Confirmados contra la API real: SF, SA, BA, JY, C.
export const AR_PROVINCES = [
  { code: "BA", name: "Buenos Aires" },
  { code: "C", name: "Ciudad Autónoma de Buenos Aires" },
  { code: "CA", name: "Catamarca" },
  { code: "CC", name: "Chaco" },
  { code: "CH", name: "Chubut" },
  { code: "CB", name: "Córdoba" },
  { code: "CN", name: "Corrientes" },
  { code: "ER", name: "Entre Ríos" },
  { code: "FO", name: "Formosa" },
  { code: "JY", name: "Jujuy" },
  { code: "LP", name: "La Pampa" },
  { code: "LR", name: "La Rioja" },
  { code: "MZ", name: "Mendoza" },
  { code: "MN", name: "Misiones" },
  { code: "NQ", name: "Neuquén" },
  { code: "RN", name: "Río Negro" },
  { code: "SA", name: "Salta" },
  { code: "SJ", name: "San Juan" },
  { code: "SL", name: "San Luis" },
  { code: "SC", name: "Santa Cruz" },
  { code: "SF", name: "Santa Fe" },
  { code: "SE", name: "Santiago del Estero" },
  { code: "TF", name: "Tierra del Fuego" },
  { code: "TM", name: "Tucumán" },
] as const;
